// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// ResponseGen is an autogenerated mock type for the ResponseGen type
type ResponseGen struct {
	mock.Mock
}

// Execute provides a mock function with given fields: c, code, data, err
func (_m *ResponseGen) Execute(c *gin.Context, code int, data map[string]interface{}, err string) {
	_m.Called(c, code, data, err)
}
