// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	middleware "github.com/dino16m/GinSessionMW/middleware"
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// SessionFunc is an autogenerated mock type for the SessionFunc type
type SessionFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: c
func (_m *SessionFunc) Execute(c *gin.Context) middleware.Session {
	ret := _m.Called(c)

	var r0 middleware.Session
	if rf, ok := ret.Get(0).(func(*gin.Context) middleware.Session); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(middleware.Session)
		}
	}

	return r0
}
