// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// UnauthorizedFunc is an autogenerated mock type for the UnauthorizedFunc type
type UnauthorizedFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: c
func (_m *UnauthorizedFunc) Execute(c *gin.Context) {
	_m.Called(c)
}
